USE clinica_vet; 

-- DB CLINICA VET

-- TABELA CLIENTE

INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Patricia Johnson", "Workhaven Lane 23", 11951009653, "patricia.johnson@gmail.com", 19574179113);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Linda Williams", "Lillydale Drive 1411", 11924455222, "linda.williams@gmail.com", 12938923155);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Barbara Jones", "Hanoi Way 1913", 11982181037, "barbara.jones@gmail.com", 44947611200);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Matthew Mahan", "Joliet Street 1121", 11906367268, "matthew.mahan@hotmail.com", 38047827859);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Timothy Bunn", "Santiago de Compostela Parkway 1795", 11915525745, "timothy.bunn@hotmail.com", 23055982286);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Jose Andrew", "Joliet Way 900", 11938788466, "jose.andrew@hotmail.com", 38664921453);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Alfredo Mcadams", "Santo Andr Manor 966", 11969920710, "alfredo.mcadams@gmail.com", 25241563344);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Alberto Henning", "Iligan Lane 770", 11933427977, "alberto.henning@gmail.com", 41520005252);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Eric Robert", "Aden Boulevard 1485", 11973956528, "eric.robert@hotmail.com", 10221543034);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Stephen Qualls", "Toulouse Parkway 419", 11954389850, "stephen.qualls@hotmail.com", 14093969494);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Sharon Robinson", "Toulon Boulevard 360", 11934145599, "sharon.robinson@gmail.com", 32445759630);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Carol Garcia", "Brest Avenue 270", 11954086212, "carol.garcia@gmail.com", 14272676130);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Sarah Lewis", "Charlotte Amalie Street 262", 11979440378, "sarah.lewis@gmail.com", 17392567923);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Nicholas Barfield", "Tafuna Way 1780", 11922322574, "nicholas.barfield@hotmail.com", 37782872029);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Victor Barkley", "San Felipe de Puerto Plata Street 96", 11922107005, "victor.barkley@hotmail.com", 41515094818);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Martin Bales", "Duisburg Boulevard 934", 11942398703, "martin.bales@hotmail.com", 29302615975);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Rebecca Scott", "Botshabelo Place 18", 11900444927, "rebecca.scott@gmail.com", 10720084945);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Pamela Baker", "Aurora Avenue 1425", 11954925684, "pamela.baker@gmail.com", 37270276483);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Martha Gonzalez", "Gorontalo Way 33", 11921711775, "martha.gonzalez@gmail.com", 37333968739);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Amanda Carter", "Mandaluyong Place 176", 11927807358, "amanda.carter@gmail.com", 36591751305);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Stephanie Mitchell", "Tama Street 61", 11955666667, "stephanie.mitchell@gmail.com", 20155137770);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Christine Roberts", "Callao Drive 391", 11905112779, "christine.roberts@gmail.com", 29433031912);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Marie Turner", "Munger (Monghyr) Lane 334", 11933060463, "marie.turner@gmail.com", 80254436340);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Alice Stewart", "Cam Ranh Parkway 269", 11943413283, "alice.stewart@gmail.com", 20168413181);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Sylvia Ortiz", "Antofagasta Place 306", 11915875315, "sylvia.ortiz@hotmail.com", 25126450336);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Josephine Gomez", "Graz Street 671", 11978095243, "josephine.gomez@hotmail.com", 22189263680);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Thelma Murray", "Brindisi Place 42", 11952674483, "thelma.murray@hotmail.com", 26993243870);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Elizabeth Brown", "Pjatigorsk Lane 1718", 11984941020, "elizabeth.brown@gmail.com", 23898881467);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Jennifer Davis", "Garland Manor 46", 11985767453, "jennifer.davis@gmail.com", 24644470878);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Maria Miller", "Garland Manor 686", 11908069636, "maria.miller@gmail.com", 14532261380);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Helen Harris", "Isesaki Place 909", 11904844121, "helen.harris@gmail.com", 15344365491);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Ivan Cromwell", "Hidalgo Parkway 725", 11928881259, "ivan.cromwell@gmail.com", 42831685593);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Sergio Stanfield", "Probolinggo Loop 1135", 11947623233, "sergio.stanfield@gmail.com", 32060830006);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Deborah Walker", "Kabul Boulevard 939", 11982646202, "deborah.walker@gmail.com", 59065997880);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Jessica Hall", "Hodeida Way 1213", 11912350516, "jessica.hall@gmail.com", 24129577622);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Ana Bradley", "Ponce Place 81", 11936303937, "ana.bradley@hotmail.com", 38423116639);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Tamara Nguyen", "Otsu Street 1966", 11962037330, "tamara.nguyen@hotmail.com", 12528657131);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Marlene Welch", "Cam Ranh Street 1124", 11924851291, "marlene.welch@hotmail.com", 40703376775);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Lydia Burke", "Poos de Caldas Boulevard 89", 11946743452, "lydia.burke@hotmail.com", 29282321860);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Joseph Joy", "Dos Quebradas Place 1947", 11932133320, "joseph.joy@hotmail.com", 41147678399);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Thomas Grigsby", "Salzburg Lane 1692", 11917950072, "thomas.grigsby@hotmail.com", 45482517879);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Christopher Greco", "Citt del Vaticano Boulevard 929", 11998871482, "christopher.greco@hotmail.com", 32459919481);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Daniel Cabral", "Firozabad Loop 1599", 11948463610, "daniel.cabral@hotmail.com", 31028229013);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Sheila Wells", "Vila Velha Manor 669", 11929960583, "sheila.wells@hotmail.com", 35212597721);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Antonio Meek", "Mandaluyong Place 1913", 11940765114, "antonio.meek@hotmail.com", 42859715900);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Tony Carranza", "Junan Way 1002", 11982895614, "tony.carranza@hotmail.com", 21702825716);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Luis Yanez", "Elista Drive 682", 11910617469, "luis.yanez@hotmail.com", 20315758977);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Leonard Schofield", "Belm Manor 758", 11954988466, "leonard.schofield@hotmail.com", 36465078998);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Nathan Runyon", "Saint Louis Way 1752", 11968174487, "nathan.runyon@hotmail.com", 40913791630);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Vincent Ralston", "Southampton Drive 898", 11973809543, "vincent.ralston@hotmail.com", 22056456190);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Alexander Fennell", "Johannesburg Avenue 261", 11990435935, "alexander.fennell@hotmail.com", 11241296720);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Bernard Colby", "Sunnyvale Avenue 126", 11900161591, "bernard.colby@hotmail.com", 37435434936);
INSERT INTO cliente (nome_cliente, endereco_cliente, telefone_cliente, email_cliente, cpf_cliente) VALUES	("Mario Cheatham", "So Bernardo do Campo Lane 913", 11973459539, "mario.cheatham@hotmail.com", 12638164472);


-- TABELA PACIENTE

INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Belinha", "canino", "poodle", "F", "branco", "2010-08-23", "S", 8.3, 1);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Thor", "canino", "pitbull", "M", "cinza", "2020-09-22", "N", 18.6, 2);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Leona", "canino", "SRD", "F", "caramelo", "2021-05-05", "S", 20.1, 3);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Bob", "canino", "shih tzu", "M", "bege", "2008-10-10", "S", 4.3, 4);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Oscar", "felino", "SRD", "M", "tigrado com branco", "2021-05-08", "S", 5.5, 5);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Tadeu", "felino", "SRD", "M", "tigrado com branco ", "2021-05-09", "S", 5.4, 5);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Margo", "felino", "SRD", "F", "preto e branco", "2014-03-01", "S", 5.6, 6);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Lulu", "canino", "lhasa apso", "F", "marrom ", "2020-03-20", "N", 4.8, 7);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Batata", "felino", "SRD", "M", "preto e branco", "2014-04-02", "S", 6.3, 8);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Amora", "felino", "SRD", "F", "preto", "2018-06-10", "S", 5.2, 9);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Mel", "canino", "yorkshire", "F", "caramelo", "2018-09-22", "S", 3.0, 10);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Amora", "canino", "SRD", "F", "preto", "2019-08-23", "S", 10.0, 11);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Pérola", "felino", "persa", "F", "branco", "2021-10-01", "N", 4.2, 12);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Jade", "felino", "persa", "F", "branco", "2021-10-01", "N", 4.3, 13);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Princesa", "felino", "SRD", "F", "bege e branco", "2018-08-15", "S", 4.0, 13);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Arya", "felino", "siamês ", "F", "bege e marrom ", "2021-01-01", "S", 3.9, 14);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Fred", "felino", "SRD", "M", "laranja", "2020-03-20", "N", 6.0, 15);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Thor", "canino", "labrador", "M", "caramelo", "2020-03-20", "S", 23.1, 16);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Coralina", "canino", "border collie", "F", "marrom e branco", "2013-02-18", "S", 15.5, 17);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Gatoso", "felino", "sphynx", "M", "não tem ", "2017-01-01", "N", 4.0, 18);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Coca-cola", "felino", "SRD", "F", "preto", "2022-08-15", "N", 1.1, 19);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Guaraná", "felino", "SRD", "M", "laranja", "2022-08-15", "N", 1.1, 19);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Fanta", "felino", "SRD", "M", "tricolor", "2022-08-15", "N", 1.3, 19);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Princesa", "canino", "SRD", "F", "caramelo", "2017-10-04", "S", 12.5, 20);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Belinha", "canino", "poodle", "F", "branca", "2013-12-01", "S", 6.8, 21);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Amora", "canino", "golden ", "F", "caramelo", "2015-04-12", "N", 20.7, 21);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Vicky", "canino", "SRD", "F", "preto e branco", "2012-03-10", "S", 37.8, 22);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Binho", "felino", "SRD", "M", "laranja", "2020-03-20", "S", 6.3, 23);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Lady ", "felino", "maine coon ", "F", "tigrado", "2020-01-01", "N", 6.3, 24);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Bill", "canino", "american bully", "M", "branco", "2018-05-29", "N", 30.0, 25);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Tequila", "felino", "SRD", "M", "branco", "2017-09-27", "S", 5.1, 26);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Vitoria", "felino", "SRD", "F", "tricolor", "2017-10-04", "S", 4.7, 27);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Mel", "canino", "lhasa apso", "F", "marrom e preto", "2019-11-20", "S", 4.2, 28);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Zeus", "felino", "SRD", "M", "bege e branco0", "2018-12-10", "N", 5.3, 29);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Billy", "felino", "SRD", "M", "preto", "2019-03-23", "S", 6.0, 30);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Gege", "felino", "SRD", "M", "preto", "2017-05-20", "S", 5.1, 30);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Zara", "canino", "pitbull", "F", "preto e branco", "2016-12-20", "S", 38.5, 31);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Thor", "canino", "american bully", "M", "marrom e branco", "2018-03-01", "N", 33.5, 32);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("July", "felino", "SRD", "F", "preto", "2021-05-08", "S", 4.9, 33);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Bruce", "canino", "labrador", "F", "marrom", "2019-05-19", "S", 27.8, 34);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Lance", "canino", "pointer alemão", "M", "marrom e branco", "2019-01-01", "S", 42.0, 35);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Judith", "felino", "SRD", "F", "preto e branco", "2019-11-24", "S", 4.4, 35);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Lua", "felino", "sphynx", "F", "não tem ", "2018-06-10", "S", 5.0, 36);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Amora", "felino", "SRD", "F", "tigrado", "2017-06-10", "S", 5.0, 37);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Percy", "felino", "SRD", "M", "laranja", "2018-05-14", "S", 6.3, 38);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Chilo", "canino", "spitz", "M", "caramelo", "2022-02-10", "N", 4.4, 39);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Mãezinha", "canino", "spitz", "F", "preto", "2021-08-20", "S", 5.0, 39);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Florzinha", "canino", "spitz", "F", "preto", "2022-02-10", "N", 4.7, 39);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Amora", "canino", "golder", "F", "caramelo", "2019-11-24", "S", 27.4, 40);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Tequila", "felino", "SRD", "F", "tricolor", "2018-03-01", "S", 4.9, 41);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Whisky ", "felino", "SRD", "M", "laranja ", "2018-03-01", "S", 5.7, 41);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Lulu", "canino", "shih tzu", "F", "cinza e branco", "2017-04-12", "S", 5.0, 42);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Toto", "canino", "SRD", "M", "cinza e preto", "2014-08-30", "S", 17.0, 43);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Charlie", "felino", "SRD", "M", "cinza e branco", "2022-07-10", "N", 3.0, 44);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Leona", "canino", "SRD", "F", "marrom", "2019-05-24", "S", 15.4, 45);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Bill", "canino", "pitbull", "M", "marrom ", "2018-12-25", "S", 19.1, 45);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Zeus", "felino", "SRD", "M", "branco", "2019-10-10", "S", 5.3, 46);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Tadeu", "felino", "SRD", "M", "laranja", "2022-09-09", "N", 2.5, 47);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Gaia", "felino", "maine coon ", "F", "tigrado", "2022-06-29", "S", 4.9, 48);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Florzinha", "canino", "shih tzu", "F", "cinza", "2020-09-09", "S", 5.0, 49);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Lua", "felino", "SRD", "F", "tigrado", "2020-05-20", "S", 5.5, 50);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Princesa", "canino", "yorkshire", "F", "caramelo e preto", "2019-11-24", "S", 3.8, 51);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Leona", "canino", "SRD", "M", "caramelo", "2022-01-19", "S", 8.3, 52);
INSERT INTO paciente (nome_paciente, especie, raca, sexo, pelagem, nascimento_paciente, castrado, peso, id_cliente) VALUES 	("Mimi", "felino", "SRD", "F", "branco ", "2018-07-30", "S", 5.7, 53);

-- TABELA PAGAMENTO

INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(260, 1, 1);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 2, 2);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(115, 3, 3);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 4, 4);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(120, 5, 5);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(120, 5, 6);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(170, 6, 7);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 7, 8);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 8, 9);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 9, 10);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(105, 10, 11);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(95, 11, 12);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(55, 12, 13);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 13, 14);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 13, 15);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(100, 14, 16);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 15, 17);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 16, 18);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 17, 19);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 18, 20);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(75, 19, 21);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(75, 19, 22);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(75, 19, 23);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 20, 24);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(120, 21, 25);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 21, 26);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(95, 22, 27);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(100, 23, 28);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 24, 29);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(115, 25, 30);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(170, 26, 31);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 27, 32);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 28, 33);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(100, 29, 34);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 30, 35);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(120, 30, 36);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 31, 37);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(110, 32, 38);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(250, 17, 19);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 6, 7);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(250, 33, 39);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(115, 34, 40);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(115, 35, 41);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 35, 42);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 36, 43);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 37, 44);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 38, 45);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 39, 46);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 39, 47);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 39, 48);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(105, 40, 49);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(100, 41, 50);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 41, 51);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(170, 42, 52);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(210, 27, 32);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 21, 25);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(260, 43, 53);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(100, 44, 54);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(95, 45, 55);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(95, 45, 56);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(120, 46, 57);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 15, 17);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(75, 47, 58);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(100, 48, 59);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(110, 49, 60);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(120, 50, 61);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 51, 62);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 13, 14);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(0, 13, 15);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(70, 52, 63);
INSERT INTO pagamento (valor_pagamento, id_cliente, id_paciente) VALUES	(100, 53, 64);

-- TABELA MEDICO_VETERINARIO 

INSERT INTO medico_veterinario (nome_mv, telefone_mv, email_mv, cpf_mv, crmv, especialidade) VALUES	("Thalita de Brito", 11999106258, "thalita.britovet@gmail.com", 32242663055 , "49933SP", "clínica de pequenos animais");
INSERT INTO medico_veterinario (nome_mv, telefone_mv, email_mv, cpf_mv, crmv, especialidade) VALUES	("Vitória Gillioli", 11923800583, "vitoria.gillioli@hotmail.com", 46530529606, "57007SP", "clínica de pequenos animais");
INSERT INTO medico_veterinario (nome_mv, telefone_mv, email_mv, cpf_mv, crmv, especialidade) VALUES	("Thiago Chagas", 21941530148, "thiago_orto@hotmail.com", 14174590809, "40524RJ", "ortopedia");
INSERT INTO medico_veterinario (nome_mv, telefone_mv, email_mv, cpf_mv, crmv, especialidade) VALUES	("Tânia Fernandes", 11988480476, "tania.fernandes@hotmail.com", 15265058449, "1848SP", "dermatologia");

-- TABELA ESTAGIARIO

INSERT INTO estagiario (nome_estagiario, telefone_estagiario, email_estagiario, cpf_estagiario, instituicao_ensino, tipo_estagio) VALUES	("Lorena Grecco", 11990872660, "loogreco@gmail.com", 38342632627, "Universidade Anhembi Morumbi", "obrigatório");
INSERT INTO estagiario (nome_estagiario, telefone_estagiario, email_estagiario, cpf_estagiario, instituicao_ensino, tipo_estagio) VALUES	("Gabriela Ayumi", 11975007954, "ayumi@hotmail.com", 44931804490, "Faculdade Anhaguera", "obrigatório");
INSERT INTO estagiario (nome_estagiario, telefone_estagiario, email_estagiario, cpf_estagiario, instituicao_ensino, tipo_estagio) VALUES	("Bianca Rossi", 11914007459, "biarossi99@gmail.com", 42661466650, "Faculdades Metropolitanas Unidas", "extracurricular");
INSERT INTO estagiario (nome_estagiario, telefone_estagiario, email_estagiario, cpf_estagiario, instituicao_ensino, tipo_estagio) VALUES	("Gabriel Moraes", 11979644830, "gab_moraes@gmail.com", 40759769238, "Universidade Metodista de São Paulo", "obrigatório");

-- TABELA CONSULTA

INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "08:30", 4, 2, "dermatologia", 1, 1, 1);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "08:30", 1, 4, "clínica", 2, 2, 2);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "09:00", 1, 4, "vacinação", 3, 3, 3);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "10:00", 4, 2, "dermatologia", 4, 4, 4);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "10:30", 1, 4, "vacinação", 5, 5, 5);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "10:50", 1, 4, "vacinação", 5, 6, 6);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "11:30", 1, 4, "clínica", 6, 7, 7);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "12:00", 1, 4, "clínica", 7, 8, 8);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "13:00", 1, 4, "clínica", 8, 9, 9);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "14:30", 2, 1, "clínica", 9, 10, 10);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "15:00", 2, 1, "vacinação", 10, 11, 11);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "15:30", 2, 1, "vacinação", 11, 12, 12);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "16:00", 2, 1, "vacinação", 12, 13, 13);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "16:30", 2, 1, "clínica", 13, 14, 14);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "17:00", 2, 1, "clínica", 13, 15, 15);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-10", "18:00", 2, 1, "vacinação", 14, 16, 16);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-11", "08:30", 1, 4, "clínica", 15, 17, 17);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-11", "09:30", 1, 4, "vacinação", 16, 18, 18);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-11", "10:00", 1, 4, "clínica", 17, 19, 19);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-11", "10:30", 1, 4, "clínica", 18, 20, 20);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-11", "11:30", 1, 4, "vacinação", 19, 21, 21);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-11", "11:50", 1, 4, "vacinação", 19, 22, 22);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-11", "12:20", 1, 4, "vacinação", 19, 23, 23);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-11", "14:00", 1, 4, "clínica", 20, 24, 24);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-11", "15:10", 2, 1, "clínica", 21, 25, 25);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-11", "16:00", 2, 1, "clínica", 21, 26, 26);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-11", "17:00", 2, 1, "vacinação", 22, 27, 27);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-11", "17:30", 2, 1, "vacinação", 23, 28, 28);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-11", "17:30", 2, 1, "clínica", 24, 29, 29);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-11", "18:30", 2, 1, "vacinação", 25, 30, 30);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-12", "09:00", 1, 4, "clínica", 26, 31, 31);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-12", "10:00", 1, 4, "clínica", 27, 32, 32);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-12", "10:30", 1, 4, "clínica", 28, 33, 33);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-12", "12:00", 1, 4, "vacinação", 29, 34, 34);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-12", "13:00", 1, 4, "clínica", 30, 35, 35);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-12", "13:30", 1, 4, "vacinação", 30, 36, 36);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-12", "14:00", 3, 3, "ortopedia", 31, 37, 37);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-12", "15:00", 2, 1, "vacinação", 32, 38, 38);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-12", "15:00", 3, 3, "ortopedia", 17, 19, 39);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-12", "15:30", 2, 1, "clínica", 6, 7, 40);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-12", "16:00", 3, 3, "ortopedia", 33, 39, 41);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-12", "16:30", 2, 1, "vacinação", 34, 40, 42);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-12", "17:30", 2, 1, "vacinação", 35, 41, 43);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-12", "18:00", 2, 1, "clínica", 35, 42, 44);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-13", "08:00", 1, 4, "clínica", 36, 43, 45);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-13", "09:00", 1, 4, "clínica", 37, 44, 46);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-13", "10:00", 1, 4, "clínica", 38, 45, 47);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-13", "11:30", 1, 4, "vacinação", 39, 46, 48);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-13", "11:50", 1, 4, "vacinação", 39, 47, 49);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-13", "12:10", 1, 4, "vacinação", 39, 48, 50);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-13", "13:30", 1, 4, "vacinação", 40, 49, 51);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-13", "14:30", 2, 1, "vacinação", 41, 50, 52);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-13", "15:00", 2, 1, "clínica", 41, 51, 53);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-13", "16:00", 2, 1, "clínica", 42, 52, 54);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-13", "16:30", 4, 2, "dermatologia", 27, 32, 55);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-13", "17:00", 2, 1, "clínica", 21, 25, 56);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-13", "18:00", 4, 2, "dermatologia", 43, 53, 57);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-13", "18:30", 2, 1, "vacinação", 44, 54, 58);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-14", "08:30", 1, 4, "vacinação", 45, 55, 59);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-14", "08:50", 1, 4, "vacinação", 45, 56, 60);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-14", "10:00", 1, 4, "clínica", 46, 57, 61);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-14", "10:30", 1, 4, "clínica", 15, 17, 62);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-14", "11:30", 1, 4, "vacinação", 47, 58, 63);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-14", "12:00", 1, 4, "vacinação", 48, 59, 64);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-14", "13:00", 2, 1, "vacinação", 49, 60, 65);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-14", "14:30", 2, 1, "vacinação", 50, 61, 66);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-14", "15:00", 2, 1, "clínica", 51, 62, 67);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-14", "16:30", 2, 1, "clínica", 13, 14, 68);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-14", "17:30", 2, 1, "clínica", 13, 15, 69);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-14", "18:00", 2, 1, "clínica", 52, 63, 70);
INSERT INTO consulta (data_consulta, hora_consulta, id_mv, id_estagiario, tipo_consulta, id_cliente, id_paciente, id_pagamento) VALUES	("2022-10-14", "18:30", 2, 1, "vacinação", 53, 64, 71);

-- TABELA TRATAMENTO 

INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(1, 4, "medicamentoso", "2022-10-10");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(2, 1, "medicamentoso", "2022-10-10");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(7, 1, "medicamentoso", "2022-10-10");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(8, 1, "medicamentoso", "2022-10-10");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(20, 1, "medicamentoso", "2022-10-11");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(25, 2, "medicamentoso", "2022-10-11");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(31, 1, "medicamentoso", "2022-10-12");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(32, 1, "medicamentoso", "2022-10-12");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(35, 1, "medicamentoso", "2022-10-12");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(39, 3, "medicamentoso", "2022-10-12");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(41, 3, "cirúrgico", "2022-10-12");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(44, 2, "medicamentoso", "2022-10-12");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(45, 1, "medicamentoso", "2022-10-13");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(54, 2, "medicamentoso", "2022-10-13");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(57, 4, "medicamentoso", "2022-10-13");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(61, 1, "medicamentoso", "2022-10-14");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(62, 1, "medicamentoso", "2022-10-14");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(67, 2, "medicamentoso", "2022-10-14");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(69, 2, "medicamentoso", "2022-10-14");
INSERT INTO tratamento (id_consulta, id_mv, tipo_tratamento, data_consulta) VALUES	(70, 2, "medicamentoso", "2022-10-14");

-- TABELA REMEDIO 

INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(1, "Meticorten 5mg", "1 cp VO SID - 5 dias", "antialérgico");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(2, "Gaviz 10mg", "1 cp VO BID - 10 dias", "protetor gástrico");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(3, "Cronidor 12mg", "1 cp VO BID - 5 dias", "analgésico");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(3, "Prediderm 5mg", "1 cp VO SID - 5 dias", "antiinflamatório ");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(4, "Dipirona ", "5 gotas VO TID - 5 dias", "analgésico");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(4, "Agemoxi 50mg", "1/4 cp VO BID - 7 dias", "antibiótico ");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(5, "Still", "1 gota cada olho BID - 10 dias", "colírio");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(6, "Cronidor 12mg", "1 cp VO BID - 7 dias", "analgésico");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(6, "Agemoxi 50mg", "1/2 cp VO BID - 7 dias", "antibiótico ");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(7, "Dipirona ", "7 gotas VO TID - 3 dias", "analgésico");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(8, "Itraconazol 100 mg", "1 cap VO SID - 30 dias", "antifúngico ");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(9, "Lactobac Cat ", "2 mg VO SID - 15 dias", "probiótico ");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(10, "Condroplex 500mg", "1 cp VO SID - 60 dias ", "suplemento ");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(12, "Ograx 500mg", "1 cp VO SID - 30 dias", "suplemento ");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(13, "Vetaglós 50g", "1 medida da espátula BID - 10 dias ", "pomada cicatrizante ");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(14, "Dipirona ", "5 gotas VO TID - 3 dias ", "analgésico");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(15, "Prediderm 5mg", "1 + 1/2 cp VO BID - 5 dias ", "antiinflamatório ");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(16, "Agemoxi 50mg", "1/4 cp VO BID - 7 dias", "antibiótico ");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(17, "Silimarina 200mg", "1 ml VO SID - 60 dias ", "protetor hepático ");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(18, "Hemolitan Pet 30 ml", "1 ml VO BID - 10 dias ", "suplemento ");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(19, "Otoguard 20 ml", "2 gotas cada ouvido BID - 5 dias", "otológico ");
INSERT INTO remedio (id_tratamento, nome_remedio, qtd_utilizada, categoria) VALUES	(20, "Drontal Puppy", "3 doses de 2 ml VO SID - 3 dias seguidos ", "vermífugo ");

-- TABELA VACINACAO

INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(3, 1, "2022-10-10", "V10 e raiva", "320/11 e 508/22", "2023-10-10");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(5, 1, "2022-10-10", "V5 e raiva", "123/22 e 508/22", "2023-10-10");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(6, 1, "2022-10-10", "V5 e raiva", "123/22 e 508/23", "2023-10-11");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(11, 2, "2022-10-10", "giardíase e gripe", "456/22 e 378/22", "2022-11-10");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(12, 2, "2022-10-10", "V8 e raiva", "245/22 e 508/22", "2023-10-10");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(13, 2, "2022-10-10", "V4", "350/22", "2022-11-10");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(16, 2, "2022-10-10", "V4 e raiva", "350/22 e 508/22", "2023-10-10");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(18, 1, "2022-10-11", "V10 ", "320/22", "2022-11-11");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(21, 1, "2022-10-11", "V5 ", "123/22", "2022-11-11");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(22, 1, "2022-10-11", "V6", "123/22", "2022-11-11");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(23, 1, "2022-10-11", "V5 e raiva", "123/22 e 508/22", "2023-10-11");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(27, 2, "2022-10-11", "V8 e raiva", "245/22 e 508/22", "2023-10-11");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(28, 2, "2022-10-11", "V4 e raiva", "350/22 e 508/22", "2023-10-11");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(30, 1, "2022-10-11", "V10 e raiva", "508/22 e 320/22", "2023-10-11");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(34, 1, "2022-10-12", "V4 e raiva", "350/22 e 508/22", "2023-10-12");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(36, 1, "2022-10-12", "V5 e raiva", "123/22 e 510/22", "2023-10-12");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(38, 2, "2022-10-12", "giardíase e raiva", "456/22 e 510/22", "2023-10-12");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(42, 2, "2022-10-12", "V10 e raiva", "320/22 e 510/22", "2023-10-12");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(43, 2, "2022-10-12", "V10 e raiva", "320/22 e 510/22", "2023-10-12");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(48, 1, "2022-10-13", "V10 ", "320/22", "2022-11-13");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(49, 1, "2022-10-13", "V11", "320/22", "2022-11-13");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(50, 1, "2022-10-13", "V12", "320/22", "2022-11-13");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(51, 1, "2022-10-13", "raiva e gripe", "510/22 e 378/22", "2022-11-13");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(52, 2, "2022-10-13", "V4 e raiva", "350/22 e 510/22", "2023-10-13");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(58, 2, "2022-10-13", "V4 e raiva", "350/22 e 510/22", "2023-10-13");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(59, 1, "2022-10-14", "V8 e raiva", "245/22 e 510/22", "2023-10-14");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(60, 1, "2022-10-14", "V8 e raiva", "245/22 e 510/22", "2023-10-14");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(63, 1, "2022-10-14", "V5", "123/22", "2022-11-14");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(64, 1, "2022-10-14", "V4 e raiva", "305/22 e 510/22", "2023-10-14");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(65, 1, "2022-10-14", "giardíase e raiva", "456/22 e 518/22", "2023-10-14");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(66, 2, "2022-10-14", "V5 e raiva", "123/22 e 518/22", "2023-10-14");
INSERT INTO vacinacao (id_consulta, id_mv, data_consulta, tipo_vacina, lote_vacina, data_revacina) VALUES	(71, 2, "2022-10-14", "V4 e raiva", "350/22 e 518/22", "2023-10-14");

-- End File
